version: 0.2

phases:
  build:
    commands:
      - echo Attempting to build with gradle...
      - docker run --rm --user "$(id -u):$(id -g)"  --env GRADLE_USER_HOME=/project/.gradle -v "$PWD":/project -w /project --name gradle gradle:alpine gradle clean build jar
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo Building Docker image...
      - cp $CODEBUILD_SRC_DIR/build/libs/project-0.0.1-SNAPSHOT.jar ./build/libs/ecs-sample-0.0.1-SNAPSHOT.jar
      - docker build -t kachouh/$CODEBUILD_BUILD_ID .
      - echo Tagging Docker image with kachouh/CODEBUILD_BUILD_ID
      - docker tag kachouh/$CODEBUILD_BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID
      - echo Triggering ECS Deployment
      - docker run --rm -v $CODEBUILD_SRC_DIR/build/libs/:/usr/src/myapp -w /usr/src/myapp openjdk:8-jdk-alpine java -jar project-0.0.1-SNAPSHOT.jar --image $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID -env accessKey=$AWS_ACCESS_KEY -env secretKey=$AWS_SECRET
