version: 0.2

phases:
  build:
    commands:
      - docker run --rm --user "$(id -u):$(id -g)"  --env GRADLE_USER_HOME=/project/.gradle -v "$PWD":/project -w /project --name gradle gradle:alpine gradle clean build jar
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - cp $PWD/build/libs/project-0.0.1-SNAPSHOT.jar ./build/libs/ecs-sample-0.0.1-SNAPSHOT.jar
      - docker build -t ecs-build .
      - docker tag ecs-build $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID
      - docker run --rm $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kachouh/$CODEBUILD_BUILD_ID -env accessKey=$AWS_ACCESS_KEY -env secretKey=$AWS_SECRET
