version: 0.2

phases:
  build:
    commands:
      - echo Attempting to build with gradle...
      - docker run --rm --user "$(id -u):$(id -g)"  --env GRADLE_USER_HOME=/project/.gradle -v "$PWD":/project -w /project --name gradle gradle:alpine gradle build jar
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo Building Docker image...
      - cp $CODEBUILD_SRC_DIR/build/libs/project-0.0.1-SNAPSHOT.jar ./build/libs/ecs-sample-0.0.1-SNAPSHOT.jar
      - docker build .
      - echo Tagging Docker image with $CODEBUILD_BUILD_ID
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG